# Generated by Django 3.2.16 on 2023-08-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('cover_image_url', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=200)),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
