# Generated by Django 3.2.16 on 2023-08-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230806_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodPage',
        ),
        migrations.DeleteModel(
            name='TODO',
        ),
    ]
