# Generated by Django 3.2.16 on 2023-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230806_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=200)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedPicture',
        ),
    ]
