# Generated by Django 3.2.16 on 2023-08-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230806_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodCard2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
